### ISSUE TITLE
Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 104.

### ISSUE THREAD

**Issue by tuwid** [polettix/Bot-ChatBots-Telegram#1]
I keep getting these issue while running the sample script 

```
use Bot::ChatBots::Telegram::LongPoll;
my $lp = Bot::ChatBots::Telegram::LongPoll->new(
   token     => $ENV{TELEGRAM_API_KEY},
   processor => \&processor,
   start     => 1,
);
sub processor { # tube-compliant
   my $record = shift;
   # ... $record is normalized, by default
   return $record; # follow on..
}
```
Running it in a container  : 
```
monx-bot_1     | Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 104.
monx-bot_1     | Use of uninitialized value in addition (+) at /usr/local/lib/perl5/site_perl/5.26.1/Bot/ChatBots/Telegram/LongPoll.pm line 126.
monx-bot_1     | Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 104.
monx-bot_1     | Use of uninitialized value in addition (+) at /usr/local/lib/perl5/site_perl/5.26.1/Bot/ChatBots/Telegram/LongPoll.pm line 126.
monx-bot_1     | Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 104.
monx-bot_1     | Use of uninitialized value in addition (+) at /usr/local/lib/perl5/site_perl/5.26.1/Bot/ChatBots/Telegram/LongPoll.pm line 126.
monx-bot_1     | Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 104.
monx-bot_1     | Use of uninitialized value in addition (+) at /usr/local/lib/perl5/site_perl/5.26.1/Bot/ChatBots/Telegram/LongPoll.pm line 126.
monx-bot_1     | Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 104.
monx-bot_1     | Use of uninitialized value in addition (+) at /usr/local/lib/perl5/site_perl/5.26.1/Bot/ChatBots/Telegram/LongPoll.pm line 126.
monx-bot_1     | Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 104.
monx-bot_1     | Use of uninitialized value in addition (+) at /usr/local/lib/perl5/site_perl/5.26.1/Bot/ChatBots/Telegram/LongPoll.pm line 126.
monx-bot_1     | Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 104.
monx-bot_1     | Use of uninitialized value in addition (+) at /usr/local/lib/perl5/site_perl/5.26.1/Bot/ChatBots/Telegram/LongPoll.pm line 126.
monx-bot_1     | Use of uninitialized value in sprintf at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 104.
```
Any ideas ? 
ps: the error has a typo

**Comment by polettix** [comment]
A possible troubleshooting checklist:

- [ ] the bot is registered with BotFather in Telegram and the token collected
- [ ] environment variable `TELEGRAM_API_KEY` is set with the token from previous step
- [ ] the script gets the environment variable (e.g. double-check with a `print` to `STDERR`)

The error from [WWW::Telegram::BotAPI](https://metacpan.org/source/ROBERTOF/WWW-Telegram-BotAPI-0.09/lib/WWW/Telegram/BotAPI.pm#L104) is probably directly related to this (the token seems the only reasonable thing that might be `undef` at that line).

The one in `Bot::ChatBots::Telegram::LongPoll` could be a side effect, I'll try that out when possible.

**Comment by polettix** [comment]
I did a bit of investigation, here's what I found:

- your specific error pattern seems indeed to be related to the token being undefined, like hinted in my previous answer
- there is a bug in the current version of LongPoll in CPAN, patched applied in the version here in GitHub. This cause the "other half" of the problem
- the module (and the documentation) was missing a way to send quick answers, it was added

I'll send a trial release over to CPAN shortly, for possible release after some smoke testing in CPAN Testers. You can already use the code here in GitHub though.

**Update**: version 0.007-TRIAL is on CPAN and should address this issue.

**Comment by polettix** [comment]
Release 0.008 is in the way to CPAN.

I'm closing this issue, re-open it if the problem persists.

Thanks for reporting!

**Comment by tuwid** [comment]
@polettix Yes, the bot was registered with BotFather but I dont see any problems with that. I have this token working for other perl script ( using plain curl requests ) like 

```
      my $telegramAPI = 'https://api.telegram.org/' . $tg . '/sendmessage';
      my $response = $ua->post( $telegramAPI, {
          'chat_id' => $notifyObj->{'data'}{'telegram_id'},
          'text' => $notifyObj->{'data'}{'message'}
        });

      if($response->is_success){
        print $response->decoded_content();
        return 1;
      }
      else{
        print $response->decoded_content();
        return 0;
      }
```
where the $tg is the telegram token. 

The other two I dont really understand as I tried to hardcode the value as well and I would still have the same problem.

**Comment by tuwid** [comment]
@polettix thanks , will check the udpate
