### ISSUE TITLE
Mojo::Transaction::success is DEPRECATED

### ISSUE THREAD

**Issue by ferz** [polettix/Bot-ChatBots-Telegram#10]
Mojo returns this warning:
Mojo::Transaction::success is DEPRECATED in favor of Mojo::Transaction::result and Mojo::Transaction::error at /usr/local/lib/perl5/site_perl/WWW/Telegram/BotAPI.pm line 200.

**Comment by polettix** [comment]
Thanks Ferruccio. I've put a trial release of this module that adopts a newer version of WWW::Telegram::BotAPI which should hopefully address this warning (0.013-TRIAL), it should hit CPAN shortly.

After some CPANTESTERS time I'll release 0.0.14 for general consumption and hopefully close this Issue.

Thanks again!

**Comment by polettix** [comment]
New release 0.014 is available in CPAN, should fix this (re-open in case it doesn't!).

Ciao Ferruccio e grazie 👍
