### ISSUE TITLE
Odd number of elements in hash assignment

### ISSUE THREAD

**Issue by tuwid** [polettix/Bot-ChatBots-Telegram#2]
```
use WWW::Telegram::BotAPI;
use utf8;

# $token = 'botXXXXXX:XXXXXXXX-XXXXXXXXXXXXX';
#$token = $ENV{TELEGRAM_API_KEY}; 
#die "ERROR: a token is required!\n" unless defined $token

my $api = WWW::Telegram::BotAPI->new (
    token => 'botXXXXXX:XXXXXXXX-XXXXXXXXXXXXX'
);
```
I get this: 
``` 
Attaching to monxms_monx-bot_1
monx-bot_1  | Odd number of elements in hash assignment at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 37.
monx-bot_1  | ERROR: missing 'token' from %settings. at router_bot.pl line 8.
monxms_monx-bot_1 exited with code 255
```

**Comment by polettix** [comment]
This is an issue for [WWW::Telegram::BotAPI](https://github.com/Robertof/perl-www-telegram-botapi), not `Bot::ChatBots::Telegram`. I can only observe:

- I have no clue why this is happening. Are you 100% sure that the code you show is the same that yields that error?
- the token should not include the initial `bot` part (see [here](https://metacpan.org/source/ROBERTOF/WWW-Telegram-BotAPI-0.09/lib/WWW/Telegram/BotAPI.pm#L61))

Good luck!

**Comment by tuwid** [comment]
@polettix yes, thats exactly my code, i get the same issue even bu removing the "bot" part: 
```
#!/usr/bin/env perl
# Basic Telegram Bot implementation using WWW::Telegram::BotAPI
use strict;
use warnings;
use WWW::Telegram::BotAPI;
use utf8;

my $api = WWW::Telegram::BotAPI->new (
        token => 'xxxxx:xxxxxxx-xxxxxxxxxx' or die "ERROR: a token is required!\n"
);

```

I would get
```
Starting monxms_monx-bot_1 ... done
Attaching to monxms_monx-bot_1
monx-bot_1  | Useless use of a constant ("token") in void context at router_bot.pl line 10.
monx-bot_1  | Odd number of elements in hash assignment at /usr/local/lib/perl5/site_perl/5.26.1/WWW/Telegram/BotAPI.pm line 37.
monx-bot_1  | ERROR: missing 'token' from %settings. at router_bot.pl line 8.
monxms_monx-bot_1 exited with code 255
```

This totally doenst make sense to me. Any ideas ?

**Comment by polettix** [comment]
No real clue, sorry. I can only tell you this from my system:

    $ cat prova.pl 
    #!/usr/bin/env perl
    # Basic Telegram Bot implementation using WWW::Telegram::BotAPI
    use strict;
    use warnings;
    use WWW::Telegram::BotAPI;
    use utf8;

    my $api = WWW::Telegram::BotAPI->new (
            token => 'xxxxx:xxxxxxx-xxxxxxxxxx'
    );

    print "api<$api>\n";
    $ perl -I local/lib/perl5/ -c prova.pl 
    prova.pl syntax OK
    $ perl -I local/lib/perl5/ prova.pl 
    api<WWW::Telegram::BotAPI=HASH(0x9dbb850)>

... so everything seems fine. I also got your same error with your last script.

**Comment by tuwid** [comment]
The error was here apparently:
` token => 'xxxxx:xxxxxxx-xxxxxxxxxx' or die "ERROR: a token is required!\n" `
I changed that to  `token => 'xxxxx:xxxxxxx-xxxxxxxxxx'` and its working fine now.

That snipped was from an example gist that you posted. 
Thank you for the great work btw, the project is very nice! Keep up the good work!
