### ISSUE TITLE
maybe explain the whole Log::Any thing?

### ISSUE THREAD

**Issue by wchristian** [polettix/Bot-ChatBots-Telegram#9]
https://metacpan.org/pod/Bot::ChatBots::Telegram#SYNOPSIS brings in Log::Any, but it is nowhere mentioned why. It seems to me that it is required because otherwise error reporting kinda breaks in the guts of Bot::ChatBots?

It's a little bit of a deal for me also because i like to use Log::Contextual and it took some figuring out to know i need to do:

```perl
use Log::Any qw< $log >;
use Log::Any::Adapter;
use Log::Contextual qw' :log set_logger ';

    Log::Any::Adapter->set( $ENV{FILE} ? ( File => "./ff14t_$$.log" ) : "Stdout" );
    set_logger $log;
```
so i could do:
```perl
    slog_debug "loaded chats: " . keys %{ $data{known_chats} };
```

**Comment by polettix** [comment]
Right, thanks.

- [x] document usage of `Log::Any`, what is needed on the module  user's side and why
- [x] document how to attach `Log::Any`'s output to `Mojolicious`, if needed

**Comment by polettix** [comment]
See https://github.com/polettix/Bot-ChatBots-Telegram/commit/60634635af3b3019b1eb67515c2e37383b63b1b5. Would you write a wiki page about using `Log::Contextual`? You have been sent a collaborator invitation just in case.
